@HotelListingApi_HostAddress = http://localhost:5298

// Hotel http requests

GET {{HotelListingApi_HostAddress}}/api/hotels/
Accept: application/json

###

POST {{HotelListingApi_HostAddress}}/api/hotels/
Content-Type: application/json

{
    "name": "Zdravstvuite Test",
    "address": "ale4 Street",
    "rating": 4,
    "countryId": 2004
}

###

@hotelid=2003
DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{hotelid}}

###

GET {{HotelListingApi_HostAddress}}/api/hotels/{{hotelid}}
Accept: application/json

###

PUT {{HotelListingApi_HostAddress}}/api/hotels/{{hotelid}}
Content-Type: application/json

{
    "id": 1,
    "name": "Updated Hotel Test2",
    "address": "456 Updated Street",
    "rating": 4.8,
    "countryId": 2002
}

###

// Country http requests

GET {{HotelListingApi_HostAddress}}/api/countries/
Accept: application/json

###

POST {{HotelListingApi_HostAddress}}/api/countries/
Content-Type: application/json

{
    "name": "Pisun",
    "shortName": "PSN"
}

###

@countryId=2004
DELETE {{HotelListingApi_HostAddress}}/api/countries/{{countryId}}

###

GET {{HotelListingApi_HostAddress}}/api/countries/{{countryId}}
Accept: application/json

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{countryId}}
Content-Type: application/json

{
    "countryId": 1,
    "name": "Jamaica",
    "shortName": "JM"
}

###