@HotelListingApi_HostAddress = http://localhost:5298

// Hotel http requests

GET {{HotelListingApi_HostAddress}}/api/hotels/
Accept: application/json

###

POST {{HotelListingApi_HostAddress}}/api/hotels/
Content-Type: application/json

{
    "id": 2,
    "name": "Hotelsdgs Test",
    "address": "123 Test Street",
    "rating": 4.5
}

###

@id=2
DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Accept: application/json

###

PUT {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
    "id": 2,
    "name": "Updated Hotel Test2",
    "address": "456 Updated Street",
    "rating": 4.8
}

###

// Country http requests

GET {{HotelListingApi_HostAddress}}/api/countries/
Accept: application/json

###

POST {{HotelListingApi_HostAddress}}/api/countries/
Content-Type: application/json

{
    "name": "Kalap",
    "shortName": "KLP"
}

###

@id=1
DELETE {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Accept: application/json

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
    "countryId": 1,
    "name": "Jamaica",
    "shortName": "JM"
}

###